In [122]:
import numpy as np
from scipy.linalg import lu

# Problem 11


In [123]:
A1 = np.array([[3, -1,1], [3, 6,2],[3,3,7]])
b1 = np.array([1,0,4])
x1 = np.linalg.solve(A1, b1)

print("Solution(x):")
print(x1)

Solution(x):
[ 0.03508772 -0.23684211  0.65789474]


In [124]:
A2 = np.array([[10, -1,0], [-1, 10,-2],[0,-2,10]])
b2 = np.array([9,7,6])
x2 = np.linalg.solve(A2, b2)

print("Solution(x):")
print(x2)

Solution(x):
[0.99578947 0.95789474 0.79157895]


In [125]:
A3 = np.array([[10,5,0,0], [5,10,-4,0],[0,-2,8,-1],[0,0,-1,5]])
b3 = np.array([6,25,-11,-11])
x3 = np.linalg.solve(A3, b3)

print("Solution(x):")
print(x3)

Solution(x):
[-0.57623762  2.35247525 -1.08910891 -2.41782178]


In [126]:
A4 = np.array([[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]])
b4 = np.array([6,6,6,6,6])
x4 = np.linalg.solve(A4, b4)

print("Solution(x):")
print(x4)

Solution(x):
[ 0.78663239 -1.00257069  1.86632391  1.9125964   1.98971722]


# Problem 13

In [127]:
P1,L1,U1=lu(A1)
B1=np.dot(L1,U1)

print("Permutation:")
print(P1)

print("Lower Triangular Matrix(L):")
print(L1)

print("Upper Triangular Matrix(U):")
print(U1)

print("Matrix Product(LU):")
print(B1)

Permutation:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Lower Triangular Matrix(L):
[[1.         0.         0.        ]
 [1.         1.         0.        ]
 [1.         0.57142857 1.        ]]
Upper Triangular Matrix(U):
[[ 3.         -1.          1.        ]
 [ 0.          7.          1.        ]
 [ 0.          0.          5.42857143]]
Matrix Product(LU):
[[ 3. -1.  1.]
 [ 3.  6.  2.]
 [ 3.  3.  7.]]


In [128]:
P2,L2,U2=lu(A2)
B2=np.dot(L2,U2)

print("Permutation:")
print(P2)

print("Lower Triangular Matrix(L):")
print(L2)

print("Upper Triangular Matrix(U):")
print(U2)

print("Matrix Product(LU):")
print(B2)

Permutation:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Lower Triangular Matrix(L):
[[ 1.         0.         0.       ]
 [-0.1        1.         0.       ]
 [ 0.        -0.2020202  1.       ]]
Upper Triangular Matrix(U):
[[10.        -1.         0.       ]
 [ 0.         9.9       -2.       ]
 [ 0.         0.         9.5959596]]
Matrix Product(LU):
[[10. -1.  0.]
 [-1. 10. -2.]
 [ 0. -2. 10.]]


In [129]:
P3,L3,U3=lu(A3)
B3=np.dot(L3,U3)

print("Permutation:")
print(P3)

print("Lower Triangular Matrix(L):")
print(L3)

print("Upper Triangular Matrix(U):")
print(U3)

print("Matrix Product(LU):")
print(B3)

Permutation:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Lower Triangular Matrix(L):
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -0.26666667  1.          0.        ]
 [ 0.          0.         -0.14423077  1.        ]]
Upper Triangular Matrix(U):
[[10.          5.          0.          0.        ]
 [ 0.          7.5        -4.          0.        ]
 [ 0.          0.          6.93333333 -1.        ]
 [ 0.          0.          0.          4.85576923]]
Matrix Product(LU):
[[10.  5.  0.  0.]
 [ 5. 10. -4.  0.]
 [ 0. -2.  8. -1.]
 [ 0.  0. -1.  5.]]


In [130]:
P4,L4,U4=lu(A4)
B4=np.dot(L4,U4)

print("Permutation:")
print(P4)

print("Lower Triangular Matrix(L):")
print(L4)

print("Upper Triangular Matrix(U):")
print(U4)

print("Matrix Product(LU):")
print(B4)

Permutation:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Lower Triangular Matrix(L):
[[ 1.          0.          0.          0.          0.        ]
 [-0.25        1.          0.          0.          0.        ]
 [ 0.5        -0.18181818  1.          0.          0.        ]
 [-0.25        0.27272727 -0.23076923  1.          0.        ]
 [ 0.         -0.72727273 -0.01923077  0.48369565  1.        ]]
Upper Triangular Matrix(U):
[[ 4.          1.          1.          0.          1.        ]
 [ 0.         -2.75        1.25        1.          0.25      ]
 [ 0.          0.          4.72727273 -0.81818182 -1.45454545]
 [ 0.          0.          0.          3.53846154 -0.15384615]
 [ 0.          0.          0.          0.          4.22826087]]
Matrix Product(LU):
[[ 4.00000000e+00  1.00000000e+00  1.00000000e+00  0.00000000e+00
   1.00000000e+00]
 [-1.00000000e+00 -3.00000000e+00  1.00000000e+00  1.00000000e+00
   0.00000000e+00]
 [ 2.00000000e+00 

# Problem 16

In [131]:
A=np.array([[0.2,0.1,1,1,0],[0.1,4,-1,1,-1],[1,-1,60,0,-2],[1,1,0,8,4],[0,-1,-2,4,700]])
b=np.array([1.,2.,3.,4.,5.])
x0=np.array([1.,1.,1.,1.,1.])

In [132]:
# Jacobi method
def jacobi(A, b, x0, tol=0.01, max_iter=1000):
    """
    Solve a system of linear equations using the Jacobi method.

    Parameters:
    A (numpy.ndarray): Coefficient matrix.
    b (numpy.ndarray): Right-hand side vector.
    x0 (numpy.ndarray): Initial guess for the solution.
    tol (float): Tolerance for convergence.
    max_iter (int): Maximum number of iterations.

    Returns:
    numpy.ndarray: Solution vector.
    int: Number of iterations performed.
    """
    n = len(b)
    x = x0.copy()
    x_new = np.zeros_like(x)
    iterations = 0
    while iterations < max_iter:
        for i in range(n):
            sigma = 0
            for j in range(n):
                if j != i:
                    sigma += A[i, j] * x[j]
            x_new[i] = (b[i] - sigma) / A[i, i]
        if np.linalg.norm(x_new - x) < tol:
            break
        x = x_new.copy()
        iterations=iterations+1
    return x, iterations

# Solving by Jacobi method
solution, iterations = jacobi(A, b, x0)
print("Solution:", solution)
print("Number of iterations:", iterations)

Solution: [ 7.85378822  0.42258012 -0.07366653 -0.54129699  0.01062118]
Number of iterations: 55


In [133]:
# Gauss-Seidel method
def gauss_seidel(A, b, x0, tol=0.01, max_iter=1000):
    """
    Solve the system of linear equations Ax = b using the Gauss-Seidel method.

    Parameters:
    A: Coefficient matrix of shape (n, n).
    b: Column vector of constants of shape (n, 1).
    x0: Initial guess for solution vector x of shape (n, 1).
    tol(float): Tolerance for convergence.
    max_iter(int): Maximum number of iterations.

    Returns:
    x (numpy.ndarray): Solution vector of shape (n, 1).
    iterations (int): Number of iterations taken to converge.
    """
    n = len(b)
    x = x0.copy()
    iterations = 0
    while iterations < max_iter:
        x_new = np.zeros_like(x)
        for i in range(n):
            x_new[i] = (b[i] - np.dot(A[i, :i], x_new[:i]) - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]
        if np.linalg.norm(x_new - x) < tol:
            break
        x = x_new
        iterations=iterations+1
    return x, iterations

# Solving by Gauss-Seidel method
solution, iterations = gauss_seidel(A, b,x0)
print("Solution:", solution)
print("Number of iterations:", iterations)

Solution: [ 7.82917663  0.42249221 -0.07309154 -0.53675664  0.01060477]
Number of iterations: 18


In [134]:
# Relaxation method
def relaxation_method(A, b, x0, tolerance=0.01, max_iterations=1000, omega=1.25):
    """
    Solve a system of linear equations using the Relaxation method.

    Arguments:
    A: 2D array representing the coefficients of the linear equations
    b: 1D array representing the constants on the right-hand side of the equations
    x0: 1D array representing the initial guess for the solution
    tolerance: Desired tolerance for the solution
    max_iterations: Maximum number of iterations allowed
    omega: Relaxation parameter (typically between 1 and 2)

    Returns:
    solution: 1D array representing the solution to the system of linear equations
    num_iterations: Number of iterations performed
    """
    n = len(b)
    solution = np.copy(x0)
    for iteration in range(max_iterations):
        old_solution = np.copy(solution)
        for i in range(n):
            summation = 0.0
            for j in range(n):
                if j != i:
                    summation=summation+A[i][j] * solution[j]
            solution[i] = (1 - omega) * old_solution[i] + (omega / A[i][i]) * (b[i] - summation)
        if np.linalg.norm(solution - old_solution) < tolerance:
            return solution, iteration + 1
    print("Warning: Maximum number of iterations reached without convergence.")
    return solution, max_iterations

# Solving by Relaxation method
solution, num_iterations = relaxation_method(A, b, x0)
print("Solution:", solution)
print("Number of iterations:", num_iterations)


Solution: [ 7.85164178  0.42276815 -0.07348371 -0.53979605  0.01062204]
Number of iterations: 11


In [135]:
# Conjugate Gradient method
def conjugate_gradient(A, b, x0, tol=0.01, max_iter=1000):
    """
    Solve the linear system Ax = b using Conjugate Gradient method.

    Parameters:
        A (numpy.ndarray): Coefficient matrix.
        b (numpy.ndarray): Right-hand side vector.
        x0 (numpy.ndarray): Initial guess for the solution.
        tol (float): Tolerance for convergence.
        max_iter (int): Maximum number of iterations.

    Returns:
        x (numpy.ndarray): Solution vector.
        num_iter (int): Number of iterations performed.
    """
    r = b - np.dot(A, x0)
    p = r
    x = x0
    rsold = np.dot(r, r)
    for i in range(max_iter):
        Ap = np.dot(A, p)
        alpha = rsold / np.dot(p, Ap)
        x = x + alpha * p
        r = r - alpha * Ap
        rsnew = np.dot(r, r)
        if np.sqrt(rsnew) < tol:
            break
        p = r + (rsnew / rsold) * p
        rsold = rsnew
    return x, i+1

# Solving by Conjugate Gradient method
solution, iterations = conjugate_gradient(A, b, x0)
print("Solution:", solution)
print("Number of iterations:", iterations)


Solution: [ 7.85971308  0.42292641 -0.07359224 -0.54064302  0.01062613]
Number of iterations: 5


# Problem 17

In [136]:
def qr_eigenvalues(A, max_iter=100, tol=1e-6):
    n = A.shape[0]
    V = np.eye(n)

    for _ in range(max_iter):
        Q, R = np.linalg.qr(A)
        A = np.dot(R, Q)
        V = np.dot(V, Q)
        if np.abs(A.diagonal(-1)).max() < tol:
            break

    eigenvalues = A.diagonal()
    return eigenvalues, V

# Example matrix
A=np.array([[5,-2],[-2,8]])

# Calculate eigenvalues using QR decomposition
eigenvalues, eigenvectors = qr_eigenvalues(A)

print("Eigenvalues using QR decomposition:")
print(eigenvalues)

# Calculate eigenvalues using numpy.linalg.eigh
eigenvalues1, eigenvectors1=np.linalg.eigh(A)

print("Eigenvalues using numpy.linalg.eigh:")
print(eigenvalues1)

Eigenvalues using QR decomposition:
[9. 4.]
Eigenvalues using numpy.linalg.eigh:
[4. 9.]


# Problem 18

In [137]:
import numpy as np

def power_method(A, max_iter=1000, tol=1e-6):
    n = A.shape[0]
    x = np.random.rand(n)  # Initial guess for the eigenvector
    x /= np.linalg.norm(x)  # Normalize the initial guess

    for _ in range(max_iter):
        x_new = np.dot(A, x)
        eigenvalue = np.dot(x_new, x)
        x_new /= np.linalg.norm(x_new)  # Normalize the new eigenvector

        # Check for convergence
        if np.linalg.norm(x_new - x) < tol:
            break

        x = x_new

    return eigenvalue, x

# Example matrix
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])

# Apply Power Method to find dominant eigenvalue and eigenvector
eigenvalue, eigenvector = power_method(A)

print("Dominant eigenvalue:", eigenvalue)
print("Corresponding eigenvector:", eigenvector)


Dominant eigenvalue: 3.4142135623673537
Corresponding eigenvector: [ 0.50000142 -0.70710678  0.49999858]


# Problem 19

In [144]:
# Construction the singular value matrix
def construct_sigma(singular_values, m, n):
    # Create an empty matrix of size (m x n)
    Sigma = np.zeros((m, n))

    # Place the singular values on the diagonal
    min_dim = min(m, n)
    Sigma[:min_dim, :min_dim] = np.diag(singular_values)

    return Sigma

In [145]:
C1=np.array([[2,1],[1,0]])
U1,S1,V1=np.linalg.svd(C1)

Sigma1 = construct_sigma(S1,U1.shape[1],V1.shape[1])

D1=np.dot(np.dot(U1,Sigma1),V1)

print("Matrix(U):")
print(U1)

print("Matrix(S):")
print(Sigma1)

print("Matrix(V):")
print(V1)

print("Matrix Product(USV):")
print(D1)

Matrix(U):
[[-0.92387953 -0.38268343]
 [-0.38268343  0.92387953]]
Matrix(S):
[[2.41421356 0.        ]
 [0.         0.41421356]]
Matrix(V):
[[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]
Matrix Product(USV):
[[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -3.81016887e-17]]


In [146]:
C2=np.array([[2,1],[1,0],[0,1]])
U2,S2,V2=np.linalg.svd(C2)

Sigma2 = construct_sigma(S2,U2.shape[1],V2.shape[1])

D2=np.dot(np.dot(U2,Sigma2),V2)

print("Matrix(U):")
print(U2)

print("Matrix(S):")
print(Sigma2)

print("Matrix(V):")
print(V2)

print("Matrix Product(USV):")
print(D2)

Matrix(U):
[[-9.12870929e-01  4.80183453e-17 -4.08248290e-01]
 [-3.65148372e-01 -4.47213595e-01  8.16496581e-01]
 [-1.82574186e-01  8.94427191e-01  4.08248290e-01]]
Matrix(S):
[[2.44948974 0.        ]
 [0.         1.        ]
 [0.         0.        ]]
Matrix(V):
[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]]
Matrix Product(USV):
[[ 2.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -6.81060746e-17]
 [-1.23617226e-16  1.00000000e+00]]


In [147]:
C3=np.array([[2,1],[-1,1],[1,1],[2,-1]])
U3,S3,V3=np.linalg.svd(C3)

Sigma3 = construct_sigma(S3,U3.shape[1],V3.shape[1])

D3=np.dot(np.dot(U3,Sigma3),V3)

print("Matrix(U):")
print(U3)

print("Matrix(S):")
print(Sigma3)

print("Matrix(V):")
print(V3)

print("Matrix Product(USV):")
print(D3)

Matrix(U):
[[-0.63245553 -0.5        -0.52229321 -0.27786652]
 [ 0.31622777 -0.5        -0.30196857  0.74753928]
 [-0.31622777 -0.5         0.79704714  0.12130893]
 [-0.63245553  0.5        -0.02721464  0.59098169]]
Matrix(S):
[[3.16227766 0.        ]
 [0.         2.        ]
 [0.         0.        ]
 [0.         0.        ]]
Matrix(V):
[[-1. -0.]
 [-0. -1.]]
Matrix Product(USV):
[[ 2.  1.]
 [-1.  1.]
 [ 1.  1.]
 [ 2. -1.]]


In [148]:
C4=np.array([[1,1,0],[-1,0,1],[0,1,-1],[1,1,-1]])
U4,S4,V4=np.linalg.svd(C4)

Sigma4 = construct_sigma(S4,U4.shape[1],V4.shape[1])

D4=np.dot(np.dot(U4,Sigma4),V4)

print("Matrix(U):")
print(U4)

print("Matrix(S):")
print(Sigma4)

print("Matrix(V):")
print(V4)

print("Matrix Product(USV):")
print(D4)

Matrix(U):
[[-4.36435780e-01  7.07106781e-01  4.08248290e-01 -3.77964473e-01]
 [ 4.36435780e-01  7.07106781e-01 -4.08248290e-01  3.77964473e-01]
 [-4.36435780e-01  3.33066907e-16 -8.16496581e-01 -3.77964473e-01]
 [-6.54653671e-01  3.33066907e-16 -5.55111512e-17  7.55928946e-01]]
Matrix(S):
[[2.64575131 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]]
Matrix(V):
[[-0.57735027 -0.57735027  0.57735027]
 [ 0.          0.70710678  0.70710678]
 [ 0.81649658 -0.40824829  0.40824829]]
Matrix Product(USV):
[[ 1.00000000e+00  1.00000000e+00  2.52368982e-17]
 [-1.00000000e+00  1.27610516e-17  1.00000000e+00]
 [-8.05746207e-17  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00]]


In [149]:
C5=np.array([[0,1,1],[0,1,0],[1,1,0],[0,1,0],[1,0,1]])
U5,S5,V5=np.linalg.svd(C5)

Sigma5 = construct_sigma(S5,U5.shape[1],V5.shape[1])

D5=np.dot(np.dot(U5,Sigma5),V5)

print("Matrix(U):")
print(U5)

print("Matrix(S):")
print(Sigma5)

print("Matrix(V):")
print(V5)

print("Matrix Product(USV):")
print(D5)

Matrix(U):
[[-5.47722558e-01  3.50476164e-16  7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01 -1.48383873e-16 -5.43516408e-01
   6.36073827e-01]
 [-5.47722558e-01 -7.02388902e-17 -7.07106781e-01 -1.32058463e-01
  -4.27271064e-01]
 [-3.65148372e-01  4.08248290e-01 -1.71841615e-16  8.07633333e-01
   2.18468301e-01]
 [-3.65148372e-01 -8.16496581e-01  2.43277252e-16  1.32058463e-01
   4.27271064e-01]]
Matrix(S):
[[2.23606798 0.         0.        ]
 [0.         1.41421356 0.        ]
 [0.         0.         1.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
Matrix(V):
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-5.77350269e-01  5.77350269e-01 -5.77350269e-01]
 [-7.07106781e-01 -3.88578059e-16  7.07106781e-01]]
Matrix Product(USV):
[[-1.88904597e-16  1.00000000e+00  1.00000000e+00]
 [-7.58392910e-17  1.00000000e+00 -7.62142974e-17]
 [ 1.00000000e+00  1.00000000e+00 -3.49858899e-16]
 [-1.23350918e-16  1.00000000e+0